db_servers:
  hosts:
    db1:
      ansible_host: 52.205.174.240
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
app_servers:
  hosts:
    app1:
      ansible_host: 3.95.136.140
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    app2:
      ansible_host: 54.152.139.204
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
