db_servers:
  hosts:
    db1:
      ansible_host: 3.83.13.145
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
app_servers:
  hosts:
    app1:
      ansible_host: 54.164.175.26
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    app2:
      ansible_host: 184.72.74.164
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
